version: '3'

networks:
  inception_net:
    driver: bridge

volumes:
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/login/data/mariadb'
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/login/data/wordpress'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    networks: 
      - inception_net
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"

  wordpress:
    container_name: wordpress
    env_file: .env
    build: ./requirements/wordpress
    networks:
      - inception_net
    depends_on:
      - mariadb
    volumes:
      - db:/var/www/wordpress
    restart: unless-stopped
    expose:
      - "9000"

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    networks:
      - inception_net
    depends_on: 
      - wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    restart: on-failure
    ports:
      - "8443:443"

