version: '3.7'

# Define a custom bridge network for WordPress containers
networks:
  wp_network:
    driver: bridge

# Define named volumes for WordPress and MariaDB data persistence
volumes:
  wordpress_data:
    driver: local
  mariadb_data:
    driver: local

# Define services for MariaDB, WordPress, and Nginx
services:
  # MariaDB service configuration
  mariadb:
    container_name: mariadb_container
    build: 
      context: ./mariadb_files   # Specify build context for MariaDB Dockerfile
    env_file:
      - .env                      # Load environment variables from .env file
    volumes:
      - mariadb_data:/var/lib/mysql  # Mount MariaDB data volume
    networks:
      - wp_network                # Connect to custom bridge network
    restart: always               # Always restart container on failure

  # WordPress service configuration
  wordpress:
    container_name: wordpress_container
    build: 
      context: ./wordpress_files  # Specify build context for WordPress Dockerfile
    env_file:
      - .env                      # Load environment variables from .env file
    volumes:
      - wordpress_data:/var/www/html  # Mount WordPress data volume
    networks:
      - wp_network                # Connect to custom bridge network
    depends_on:
      - mariadb                   # Depend on MariaDB service
    restart: always               # Always restart container on failure

  # Nginx service configuration
  nginx:
    container_name: nginx_container
    build: 
      context: ./nginx_files      # Specify build context for Nginx Dockerfile
    ports:
      - "443:443"                 # Expose port 443 for SSL
    volumes:
      - wordpress_data:/var/www/html  # Mount WordPress data volume
    networks:
      - wp_network                # Connect to custom bridge network
    depends_on:
      - wordpress                # Depend on WordPress service
    restart: always               # Always restart container on failure
