version: '3'

# Define a custom bridge network named "inception_net"
networks:
  inception_net:
    name: inception_net
    driver: bridge

# Define named volumes for WordPress and MariaDB data
volumes:
  wp:
    driver: local
    name: wp
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb

# Define services for MariaDB, WordPress, and Nginx
services:
  # MariaDB service configuration
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql        # Mount the MariaDB data volume
    networks:
      - inception_net            # Connect to the custom bridge network
    restart: always              # Restart the container always

  # WordPress service configuration
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb                 # Depend on the MariaDB service
    volumes:
      - wp:/var/www/html         # Mount the WordPress data volume
    networks:
      - inception_net            # Connect to the custom bridge network
    restart: always              # Restart the container always

  # Nginx service configuration
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"                # Expose port 443 for SSL
    depends_on:
      - wordpress               # Depend on the WordPress service
    volumes:
      - wp:/var/www/html         # Mount the WordPress data volume
    networks:
      - inception_net            # Connect to the custom bridge network
    restart: always              # Restart the container always
