version: '3.7'

# Définit un réseau bridge personnalisé pour les conteneurs WordPress
networks:
  wp_network:
    driver: bridge

# Définit des volumes nommés pour la persistance des données de WordPress et MariaDB
volumes:
  wordpress_data:
    driver: local
  mariadb_data:
    driver: local

# Définit les services pour MariaDB, WordPress et Nginx
services:
  # Configuration du service MariaDB
  mariadb:
    container_name: mariadb_container
    build: 
      context: ./requirements/mariadb  # Spécifie le contexte de construction pour le Dockerfile de MariaDB
    env_file:
      - .env                      # Charge les variables d'environnement à partir du fichier .env
    volumes:
      - mariadb_data:/var/lib/mysql  # Montage du volume de données MariaDB
    networks:
      - wp_network                # Connecte au réseau bridge personnalisé
    restart: always               # Redémarrage du conteneur en cas d'échec

  # Configuration du service WordPress
  wordpress:
    container_name: wordpress_container
    build: 
      context: ./requirements/wordpress  # Spécifie le contexte de construction pour le Dockerfile de WordPress
    env_file:
      - .env                      # Charge les variables d'environnement à partir du fichier .env
    volumes:
      - wordpress_data:/var/www/html  # Montage du volume de données WordPress
    networks:
      - wp_network                # Connecte au réseau bridge personnalisé
    depends_on:
      - mariadb                   # Dépend du service MariaDB
    restart: always               # Redémarrage du conteneur en cas d'échec

  # Configuration du service Nginx
  nginx:
    container_name: nginx_container
    build: 
      context: ./requirements/nginx     # Spécifie le contexte de construction pour le Dockerfile de Nginx
    ports:
      - "443:443"                 # Expose le port 443 pour SSL
    volumes:
      - wordpress_data:/var/www/html  # Montage du volume de données WordPress
    networks:
      - wp_network                # Connecte au réseau bridge personnalisé
    depends_on:
      - wordpress                # Dépend du service WordPress
    restart: always               # Redémarrage du conteneur en cas d'échec
